TRUNCATE TABLE "Outcome-status" CASCADE;
TRUNCATE TABLE "Street" CASCADE;
TRUNCATE TABLE "Location" CASCADE;
TRUNCATE TABLE "Crimes" CASCADE;
TRUNCATE TABLE "Stop-and-search" CASCADE;

ALTER SEQUENCE "Outcome-status_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Location_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Stop-and-search_id_seq" RESTART WITH 1;